language: python
python: 3.6
env:
  - HUGO_VERSION=0.41

branches:
  only:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz hugo
  - pip install pygments
  

script:
  - git submodule update 
  - ./hugo
  - echo 'link.seispider.top' > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: ${GH_TOKEN}
  local-dir: public
